server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5 #拉取服务间隔时间（秒）
zuul:
  prefix: /api
  retryable: true
  routes:
    item-service: /item/**
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
  add-host-header: true
  sensitive-headers: #覆盖默认敏感头信息，默认会过滤cookie
leyou:
  jwt:
    pubKeyPath: C:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth #-代表一个集合，每个-后面是集合的一个元素
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item

